name: PR build and test workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  first: "value"
  second: "another value"

jobs:
  pr_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Where are we
        run: |
         echo $(pwd)
      - name: Generate path glob
        id: get-artifact-str
        shell: bash
        run: |
          set -f
          files=${{ join(fromJson('{ "wheel": "best*", tests: "random*" }').*) }}
          new_files=${{ join(fromJson('{ "wheel": "best*", tests: "random*" }').*, '\\n') }}
          echo "MY_NEW_STRING<<EOF" >> $GITHUB_OUTPUT
          echo $new_files >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          # MY_STRING=$files
          # MY_STRING=$(cat << EOF
          # $files
          # EOF
          # )
          # # MY_STRING=$(cat << EOF
          # best*
          # test*
          # random*
          # EOF
          # )
          echo "MY_STRING<<EOF" >> $GITHUB_OUTPUT
          echo "MY_STRING<<EOF" >> file.txt
          for line in ${files//,/ }; do
             echo $line >> $GITHUB_OUTPUT;
             echo $line >> file.txt;
          done
          #while IFS= read -r line ; do
          #  echo $line;
          # echo $line >> $GITHUB_OUTPUT;
          # echo $line >> file.txt;
          #done <<< "$files"
          # for file in "${files[@]}"; do
          #   echo "$file" >> $GITHUB_OUTPUT
          #   echo "$file" >> file.txt
          # done
          # echo "$MY_STRING" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "EOF" >> file.txt
          cat file.txt
          # for file in "${files[@]}"; do
            # echo "$file" >> path.txt
          # done
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: test
          if-no-files-found: error
          overwrite: true
          path: ${{ steps.get-artifact-str.outputs.MY_NEW_STRING }}
          # path: | ${{ format('\n{0}', join(fromJson('{ 32: "best_*", 64: "test_*" }').*, '\n')) }}

          #  *est_test.py
          #  test_match_case*
